### ISSUE TITLE
Twitter bot

### ISSUE THREAD

**Issue by quan-nh** [icy/fortune-vn#11]
a @icy, e viet 1 bot script post random quotes len twitter https://twitter.com/fortune_vn :)

*source: https://github.com/tentamen/fortune-vn-twit

**Comment by icy** [comment]
awesome =)) how often does the bot run? I only see one message on twitter .

**Comment by quan-nh** [comment]
once per day? not schedule yet

**Comment by icy** [comment]
yes that's good enough:) You rock. Thanks a lot. ^^
